### ISSUE TITLE
Flathub package not updating due to failing GitHub Actions

### ISSUE THREAD

**Issue by mserajnik** [flathub/com.github.tmewett.BrogueCE#17]
As already mentioned [here](https://github.com/flathub/com.github.tmewett.BrogueCE/pull/16#issuecomment-1771743921) the GitHub Actions are currently failing because the `GITHUB_TOKEN` is apparently not set; see [this job](https://github.com/flathub/com.github.tmewett.BrogueCE/actions/runs/6580542858), for example.

This prevents the package from being updated on Flathub.

**Comment by tmewett** [comment]
I don't know anything about Flatpak. It looks like the GITHUB_TOKEN is set to the FLATHUBBOT_TOKEN secret: https://github.com/flathub/com.github.tmewett.BrogueCE/actions/runs/6531216870/workflow. I don't seem to have control over repo secrets though? Maybe we need to rebase the repo onto the latest [flathub/flathub](https://github.com/flathub/flathub) repo?

**Comment by mserajnik** [comment]
Unfortunately, I don't know much about Flatpak workings either, I am mainly a user.

Comparing the workflow configurations here with the ones from [flathub/flathub](https://github.com/flathub/flathub) I don't really see any differences, so I don't think rebasing would resolve this.

It looks like the Action already failed when the commit to update to v1.12 got merged: https://github.com/flathub/com.github.tmewett.BrogueCE/actions/runs/6006143924/job/16290153443.

However, v1.12 is available on Flathub, so maybe that deployment was triggered in some other way?

The only issue I can find relating to some issue with the `GITHUB_TOKEN` is this one: https://github.com/flathub/flathub/issues/2618

Though from the comments it's not clear to me what needs to be changed to get this working either.

**Comment by mserajnik** [comment]
Unfortunately, I couldn't find any more useful information relating to the issue at hand; I think the best way to get this resolved would be to raise an issue at [flathub/flathub](https://github.com/flathub/flathub/issues), but I'll leave that decision up to you @tmewett, since you are both the developer of BrogueCE and the maintainer of this repository.

In the meantime, I've set up a small [Flatpak repository](https://github.com/mserajnik/flatpak.mser.at) on my own since I wanted to build a few applications (other roguelikes) that aren't available on Flathub.

I've also included BrogueCE 1.13 in my repository so it can be installed from there:

```sh
$ flatpak remote-add --if-not-exists flatpak.mser.at https://flatpak.mser.at/index.flatpakrepo
$ flatpak install flatpak.mser.at com.github.tmewett.BrogueCE
```

I'm using the same manifest as the one in this repository (this repository is included as submodule in mine), so everything should behave the same.

**Comment by mserajnik** [comment]
I've [opened an issue](https://github.com/flathub/flathub/issues/5003) as suggested [here](https://github.com/flathub/flathub/issues/2618#issuecomment-1782797537) to hopefully get this resolved.

**Comment by razzeee** [comment]
Both workflows in that folder seem wrong and should probably just be removed. AFAIK, it's something, that's running in the main flathub repo and shouldn't be run here. (see https://github.com/flathub/flathub/tree/master/.github/workflows)

Unsure how it ended up in this repo.

**Comment by bbhtt** [comment]
> Unsure how it ended up in this repo.

By making the submission PR against master branch of `flathub/flathub` when it was supposed to be against `new-pr`. As a result it inherited the files and commit history of `flathub/flathub`

ttps://github.com/flathub/flathub/pull/1558

**Comment by mserajnik** [comment]
@bbhtt

Thank you for looking into this.

You write [here](https://github.com/flathub/flathub/issues/5003#issuecomment-1967265644):

> You can safely remove them or ignore the failed runs.

However, we also [updated](https://github.com/flathub/com.github.tmewett.BrogueCE/commit/580a69b193c79bbaa689225270a1c9086e2260ea) to a new application version (1.13) around 4 months ago which, so far, has not been reflected on https://flathub.org/apps/com.github.tmewett.BrogueCE (where it still shows 1.12).

Is this unrelated to the failed runs (because you suggest we could also just ignore the failed runs)? If yes, what would be the cause of that? If no, will deleting those workflows also fix that issue?

**Comment by bbhtt** [comment]
The publish job or the build failed, hard to say. Build logs don't go back months, I'll trigger a rebuild.

**Comment by bbhtt** [comment]
Yep https://buildbot.flathub.org/#/builders/6/builds/74634 shows publish failed

**Comment by bbhtt** [comment]
https://buildbot.flathub.org/#/builders/6/builds/103243 is the rebuild, check the logs if it fails on something you have to fix that via PRs -> merging

Otherwise it'll be published in 4-5 hours and should reflect on the website.

**Comment by mserajnik** [comment]
Thank you, this clears things up.

I'll create a PR that removes those workflows that shouldn't exist in the first place.

**Comment by hfiguiere** [comment]
[DELETED]

nevermind

**Comment by bbhtt** [comment]
1.13 shows up no on the website
